project:
  type: book
  output-dir: docs

book:
  title: "IPUMS INTERNATIONAL"
  subtitle: "Extraction de tableaux pour l'EE CIST 2023"
  author: "Claude Grasland"
  date: "22/08/2022"
  chapters:
    - index.qmd
    - d00_02_intro_resume.qmd
    - d01_00_import_introduction.qmd
    - d01_01_import_conditions.qmd
    - d01_02_import_individus.qmd  
    - d01_03_import_geometries.qmd
    - d02_00_indicateurs_introduction.qmd
    - d02_01_indicateurs_popsup.qmd
    - d09_01_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

