project:
  type: book
  output-dir: docs

book:
  title: "EE CIST 2023 : Données de recensement harmonisées par IPUMS"
  author: "Claude Grasland"
  date: "22/08/2022"
  chapters:
    - index.qmd
    - d0001intro.qmd
    - d0002summary.qmd
    - d0101import.qmd
    - d0901references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

