project:
  type: book
  output-dir: docs

book:
  title: "L'INTERET PEDAGOGIQUE DES DONNEES IPUMS INTERNATIONAL"
  subtitle: "Une ressource majeure pour l'EE CIST 2023 ?"
  author: "Claude GRASLAND"
  date: "22/08/2022"
  chapters:
    - index.qmd
    - credits.qmd
    - d01_00_import_introduction.qmd
    - d01_01_import_conditions.qmd
    - d01_02_import_individus.qmd  
    - d01_03_import_geometries.qmd
    - d02_00_indicateurs_introduction.qmd
    - d02_01_indicateurs_popsup.qmd
    - d02_02_indicateurs_equipt.qmd
    - d02_03_indicateurs_tabcont.qmd
    - d03_00_mobil_introduction.qmd
    - d03_01_mobil_data.qmd
    - d03_02_mobil_durvie.qmd
    - d03_03_mobil_preced.qmd
    - d09_01_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

